export enum LibraryTag {
	DATA_FETCHING = "data fetching",
	DOCUMENTATION = "documentation",
	FRAMEWORKS = "frameworks",
	API_LIBRARIES = "API libraries",
	ORM = "ORM",
	TESTING = "testing",
	UTILITIES = "utilities",
	WEB_SERVERS = "web servers",
	CLI = "CLI",
	DATA_PROCESSING = "data processing",
	TEMPLATING = "templating",
	DATABASE_DRIVERS = "database drivers",
	TOOLING = "tooling",
	STATE_MANAGEMENT = "state management",
	I18N = "internationalization",
	STYLING = "styling",
	COMPONENT = "component",
	LOGGING = "logging",
	PERFORMANCE = "performance tools",
	FORMS = "forms",
	AUTH = "auth",
	HTTP_CLIENT = "http client",
	ROUTING = "routing",
	ANIMATION = "animation",
}
