import color from "color"

export const blankPalette = {
	primary100: "#ffffff",
	primary99: "#ffffff",
	primary95: "#ffffff",
	primary90: "#ffffff",
	primary80: "#ffffff",
	primary70: "#ffffff",
	primary60: "#ffffff",
	primary50: "#ffffff",
	primary40: "#ffffff",
	primary30: "#ffffff",
	primary20: "#ffffff",
	primary10: "#ffffff",
	primary0: "#ffffff",
	secondary100: "#ffffff",
	secondary99: "#ffffff",
	secondary95: "#ffffff",
	secondary90: "#ffffff",
	secondary80: "#ffffff",
	secondary70: "#ffffff",
	secondary60: "#ffffff",
	secondary50: "#ffffff",
	secondary40: "#ffffff",
	secondary30: "#ffffff",
	secondary20: "#ffffff",
	secondary10: "#ffffff",
	secondary0: "#ffffff",
	tertiary100: "#ffffff",
	tertiary99: "#ffffff",
	tertiary95: "#ffffff",
	tertiary90: "#ffffff",
	tertiary80: "#ffffff",
	tertiary70: "#ffffff",
	tertiary60: "#ffffff",
	tertiary50: "#ffffff",
	tertiary40: "#ffffff",
	tertiary30: "#ffffff",
	tertiary20: "#ffffff",
	tertiary10: "#ffffff",
	tertiary0: "#ffffff",
	neutral100: "#ffffff",
	neutral99: "#ffffff",
	neutral95: "#ffffff",
	neutral90: "#ffffff",
	neutral80: "#ffffff",
	neutral70: "#ffffff",
	neutral60: "#ffffff",
	neutral50: "#ffffff",
	neutral40: "#ffffff",
	neutral30: "#ffffff",
	neutral20: "#ffffff",
	neutral10: "#ffffff",
	neutral0: "#ffffff",
	neutralVariant100: "#ffffff",
	neutralVariant99: "#ffffff",
	neutralVariant95: "#ffffff",
	neutralVariant90: "#ffffff",
	neutralVariant80: "#ffffff",
	neutralVariant70: "#ffffff",
	neutralVariant60: "#ffffff",
	neutralVariant50: "#ffffff",
	neutralVariant40: "#ffffff",
	neutralVariant30: "#ffffff",
	neutralVariant20: "#ffffff",
	neutralVariant10: "#ffffff",
	neutralVariant0: "#ffffff",
	error100: "#ffffff",
	error99: "#ffffff",
	error95: "#ffffff",
	error90: "#ffffff",
	error80: "#ffffff",
	error70: "#ffffff",
	error60: "#ffffff",
	error50: "#ffffff",
	error40: "#ffffff",
	error30: "#ffffff",
	error20: "#ffffff",
	error10: "#ffffff",
	error0: "#ffffff",
}

export type ColorPalette = typeof blankPalette

export function lightThemeFromPalette(p: ColorPalette) {
	const surface = color(p.neutral99)
	const primary = color(p.primary40)
	return {
		palette: p,
		themeColors: {
			primary: p.primary40,
			onPrimary: p.primary100,
			primaryContainer: p.primary90,
			onPrimaryContainer: p.primary10,
			secondary: p.secondary40,
			onSecondary: p.secondary100,
			secondaryContainer: p.secondary90,
			onSecondaryContainer: p.secondary10,
			tertiary: p.tertiary40,
			onTertiary: p.tertiary100,
			tertiaryContainer: p.tertiary90,
			onTertiaryContainer: p.tertiary10,
			tertiaryBorder: p.neutral80,
			error: p.error40,
			onError: p.error100,
			errorContainer: p.error90,
			onErrorContainer: p.error10,
			background: p.neutral99,
			onBackground: p.neutral10,
			surface: surface.hex(),
			onSurface: p.neutral10,
			surfaceVariant: p.neutralVariant90,
			onSurfaceVariant: p.neutralVariant30,
			outline: p.neutralVariant50,
			regularText: p.neutral20,
			strongText: p.neutral0,
			softText: p.neutral60,
			surface1: surface.mix(primary, 0.05).hex(),
			surface2: surface.mix(primary, 0.08).hex(),
			surface3: surface.mix(primary, 0.11).hex(),
			surface4: surface.mix(primary, 0.12).hex(),
			surface5: surface.mix(primary, 0.14).hex(),
			beginner: "rgba(212, 240, 249, 0.75)",
			intermediate: "rgba(245, 228, 207, 0.75)",
			advanced: "rgba(239, 212, 212, 0.75)",
		},
	}
}

export function darkThemeFromPalette(p: ColorPalette) {
	const surface = color(p.neutral10)
	const primary = color(p.primary40)
	return {
		palette: p,
		themeColors: {
			primary: p.primary80,
			onPrimary: p.primary20,
			primaryContainer: p.primary30,
			onPrimaryContainer: p.primary90,
			secondary: p.secondary80,
			onSecondary: p.secondary20,
			secondaryContainer: p.secondary30,
			onSecondaryContainer: p.secondary90,
			tertiary: p.tertiary80,
			onTertiary: p.tertiary20,
			tertiaryBorder: p.neutral80,
			tertiaryContainer: p.tertiary30,
			onTertiaryContainer: p.tertiary90,
			error: p.error80,
			onError: p.error20,
			errorContainer: p.error30,
			onErrorContainer: p.error90,
			background: p.neutral10,
			onBackground: p.neutral90,
			surface: surface.hex(),
			onSurface: p.neutral90,
			surfaceVariant: p.neutralVariant30,
			onSurfaceVariant: p.neutralVariant80,
			outline: p.neutralVariant60,
			regularText: p.neutral80,
			strongText: p.neutral100,
			softText: p.neutral60,
			surface1: surface.mix(primary, 0.05).hex(),
			surface2: surface.mix(primary, 0.08).hex(),
			surface3: surface.mix(primary, 0.11).hex(),
			surface4: surface.mix(primary, 0.12).hex(),
			surface5: surface.mix(primary, 0.14).hex(),
			beginner: "rgba(212, 240, 249, 0.75)",
			intermediate: "rgba(245, 228, 207, 0.75)",
			advanced: "rgba(239, 212, 212, 0.75)",
		},
	}
}
