// NOTE: Please when adding a new tag make sure to have read the CONTRIBUTING.md file 📄
type CommonTagsNames =
	| "state management"
	| "data fetching"
	| "components"
	| "routing"
	| "testing"
	| "services"
	| "RxJS"
	| "javascript marathon"
	| "nx"
	| "ignite UI"
	| "ivy"
	| "PWA"
	| "A11Y"
	| "patterns"
	| "TypeScript"
	| "recipes"
	| "monorepo"
	| "NgRx"
	| "data binding"
	| "internationalization"
	| "framework"
	| "documentation"
	| "styling"
	| "logging"
	| "performance tools"
	| "redux"
	| "firebase"
	| "GraphQL"
	| "Utility-First CSS"
	| "CSS in JS"
	| "component library"
	| "bootstrap"
	| "forms"
	| "reactive forms"
	| "general"
	| "chrome"
	| "VSCode"
	| "development"
	| "UI Design"
	| "projects"
	| "authentication"
	| "material UI"
	| "flow"
	| "native"
	| "sass"
	| "CSS"
	| "tailwind"
	| "vite"
	| "AWS"
	| "netlify"
	| "continuous integration"
	| "apollo"
	| "faunaDB"
	| "3D"
	| "HTTP client"
	| "CSS processor"
	| "CSS modules"
	| "webpack"
	| "static site generation"
	| "server side rendering"
	| "storybook"
	| "animation"
	| "firefox"
	| "safari"
	| "development"
	| "projects"
	| "best practices"
	| "DevOps"
	| "debugging"
	| "Edge"

// Specific tag names for frameworks
type AngularTagsNames = "pipes"

type ReactTagsNames =
	| "NextJS"
	| "react context"
	| "hooks"
	| "GatsbyJS"
	| "react native"
	| "react.js"

type VueTagsNames =
	| "vuex"
	| "vue 2"
	| "vue 3"
	| "nuxt 2"
	| "vue CLI"
	| "nuxt"
	| "vuejs"
	| "quasar"

type TagsNames =
	| CommonTagsNames
	| AngularTagsNames
	| ReactTagsNames
	| VueTagsNames

export type Tags = readonly TagsNames[]
